version: '3'
services:
  postgres:
    image: postgres:13
    container_name: cakefest2021_postgres
    environment:
      - POSTGRES_USER=my_app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=my_app
      - PGUSER=my_app
      - PGDATABASE=my_app
      - PGPASSWORD=secret
    volumes:
      - ./:/application
    ports:
      - '5442:5432'

  php:
    image: webdevops/php-nginx-dev:8.0
    container_name: cakefest2021_cakephp
    working_dir: /application/webroot
    volumes:
      - ./:/application
    environment:
      - WEB_DOCUMENT_ROOT=/application/webroot
      - DATABASE_URL=postgres://my_app:secret@cakefest2021_postgres:5432/my_app?persistent=true
      - XDEBUG_MODE=debug,profile
      - XDEBUG_CONFIG=output_dir=/application/tmp client_host=host.docker.internal
      - CACHE_USERS_URL=redis://cakefest2021_redis:6379
      - EMAIL_TRANSPORT_DEFAULT_URL=debug://
      - QUEUE_DEFAULT_URL=redis://cakefest2021_redis:6379
    ports:
      - "8099:80"

  redis:
    image: redis:6
    container_name: cakefest2021_redis
    ports:
      - "8379:6379"
